import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#2f2ebe',
        'surface-bright': '#31394d',
        'on-tertiary-container': '#ffd2be',
        'on-secondary': '#233143',
        'on-error': '#690005',
        'surface-container-low': '#131b2e',
        'outline-variant': '#464555',
        'primary-container': '#4b4dd8',
        'surface-container-high': '#222a3d',
        'tertiary-fixed': '#ffdbcc',
        'surface-tint': '#c0c1ff',
        'secondary': '#b9c8de',
        'on-tertiary': '#571f00',
        'on-surface': '#dae2fd',
        'tertiary-container': '#a44100',
        'tertiary-fixed-dim': '#ffb695',
        'inverse-surface': '#dae2fd',
        'background': '#0b1326',
        'surface-container': '#171f33',
        'secondary-container': '#39485a',
        'on-tertiary-fixed-variant': '#7b2f00',
        'inverse-primary': '#494bd6',
        'on-error-container': '#ffdad6',
        'surface-container-lowest': '#060e20',
        'on-primary-fixed': '#07006c',
        'secondary-fixed': '#d4e4fa',
        'on-tertiary-fixed': '#351000',
        'on-secondary-fixed': '#0d1c2d',
        'on-secondary-container': '#a7b6cc',
        'on-background': '#dae2fd',
        'on-secondary-fixed-variant': '#39485a',
        'primary': '#c0c1ff',
        'tertiary': '#ffb695',
        'outline': '#918fa1',
        'surface-container-highest': '#2d3449',
        'error': '#ffb4ab',
        'surface': '#0b1326',
        'on-primary-container': '#d9d8ff',
        'surface-dim': '#0b1326',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'secondary-fixed-dim': '#b9c8de',
        'on-primary': '#1000a9',
        'on-surface-variant': '#c7c4d8',
        'inverse-on-surface': '#283044',
        'surface-variant': '#2d3449',
        'error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        '2xl': '0.75rem',
        'full': '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.4s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
